[package]
name = "rusty-gematria"
version = "0.0.1"
edition = "2021"

[profile.release]
strip = true
opt-level = 3

[dependencies]
ratatui    = "0.29"
crossterm  = "0.28"
clap       = { version = "4", features = ["derive"] }
serde      = { version = "1", features = ["derive"] }
bincode    = "1"
egui       = "0.29"
eframe     = "0.29"

[build-dependencies]
serde      = { version = "1", features = ["derive"] }
bincode    = "1"
